#!/usr/bin/env python3
"""
Generate structured Markdown files per book from Kindle highlights.
Output: data/books_md/{book_title}.md and data/books_md/LIBRARY.md

Structure per book:
- Book metadata (title, author, highlight count, reading period)
- Book summary (if available)
- Highlights organized by chapter, each with chapter summary and golden nugget context

LIBRARY.md:
- Semantic fingerprints per book generated by Gemini Flash Lite
- Personalized based on actual highlights the reader selected
"""

import argparse
import os
import re
import sqlite3
import time
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

import sys
sys.path.insert(0, str(Path(__file__).parent.parent))

from scripts.config import SUMMARY_MODEL

PROJECT_DIR = Path(__file__).parent.parent
DB_PATH = PROJECT_DIR / "data" / "kindle.db"
OUTPUT_DIR = PROJECT_DIR / "data" / "books_md"


def sanitize_filename(name: str) -> str:
    """Make a string safe for use as a filename."""
    name = re.sub(r'[<>:"/\\|?*]', '', name)
    name = name.strip('. ')
    return name[:100]


def get_gemini_client():
    """Get Google GenAI client."""
    api_key = os.getenv('GOOGLE_API_KEY')
    if not api_key:
        return None
    try:
        from google import genai
        return genai.Client(api_key=api_key)
    except ImportError:
        print("Warning: google-genai package not installed")
        return None


def generate_book_md(book_id: int, conn: sqlite3.Connection) -> str | None:
    """Generate markdown for a single book, including chapter summaries."""
    cursor = conn.cursor()

    # Book info
    cursor.execute("""
        SELECT b.title, b.author, b.summary,
               COUNT(c.id) as highlight_count,
               SUM(CASE WHEN c.rich_context IS NOT NULL THEN 1 ELSE 0 END) as nugget_count,
               MIN(c.date) as first_date, MAX(c.date) as last_date
        FROM books b
        LEFT JOIN clippings c ON b.id = c.book_id AND c.type = 'highlight'
        WHERE b.id = ?
        GROUP BY b.id
    """, (book_id,))

    row = cursor.fetchone()
    if not row or row[3] == 0:
        return None

    title, author, summary, highlight_count, nugget_count, first_date, last_date = row

    lines = []
    lines.append(f"# {title}")
    if author:
        lines.append(f"**Author**: {author}")
    lines.append(f"**Highlights**: {highlight_count}")
    if nugget_count:
        lines.append(f"**Golden Nuggets**: {nugget_count}")
    if first_date and last_date:
        lines.append(f"**Reading Period**: {first_date[:10]} — {last_date[:10]}")
    lines.append("")

    if summary:
        lines.append("## Summary")
        lines.append(summary)
        lines.append("")

    lines.append("---")
    lines.append("")

    # Pre-load chapter summaries for this book
    cursor.execute("""
        SELECT ch.id, ch.title, ch.chapter_number, ch.summary
        FROM chapters ch
        WHERE ch.book_id = ?
        ORDER BY ch.chapter_number
    """, (book_id,))
    chapter_summaries = {}
    for ch_id, ch_title, ch_num, ch_summary in cursor.fetchall():
        key = ch_title or "Uncategorized"
        chapter_summaries[key] = ch_summary

    # Get highlights organized by chapter
    cursor.execute("""
        SELECT c.text, c.surrounding_context, c.rich_context,
               c.page, c.date, c.note_text,
               ch.title as chapter_title, ch.chapter_number
        FROM clippings c
        LEFT JOIN chapters ch ON c.chapter_id = ch.id
        WHERE c.book_id = ? AND c.type = 'highlight' AND c.text IS NOT NULL
        ORDER BY c.position_start
    """, (book_id,))

    highlights = cursor.fetchall()
    current_chapter = None

    for text, surrounding, rich_context, page, date, note, ch_title, ch_num in highlights:
        # Chapter header
        chapter_key = ch_title or "Uncategorized"
        if chapter_key != current_chapter:
            current_chapter = chapter_key
            if ch_num and ch_title:
                lines.append(f"## Chapter {ch_num}: {ch_title}")
            elif ch_title:
                lines.append(f"## {ch_title}")

            # Insert chapter summary
            ch_summary = chapter_summaries.get(chapter_key)
            if ch_summary:
                lines.append("")
                lines.append(f"### Chapter Summary")
                lines.append(ch_summary)

            lines.append("")

        # Highlight
        lines.append(f"> {text}")
        lines.append("")

        # Metadata
        meta = []
        if page:
            meta.append(f"p. {page}")
        if date:
            meta.append(date[:10])
        if meta:
            lines.append(f"*{' | '.join(meta)}*")
            lines.append("")

        # Note
        if note:
            lines.append(f"**Note**: {note}")
            lines.append("")

        # Golden nugget (collapsed context)
        if rich_context:
            # Clean up markers for markdown
            clean = rich_context.replace("«««", "**→ ").replace("»»»", " ←**")
            lines.append("<details>")
            lines.append("<summary>Golden Nugget (context)</summary>")
            lines.append("")
            lines.append(clean)
            lines.append("")
            lines.append("</details>")
            lines.append("")

        lines.append("---")
        lines.append("")

    return "\n".join(lines)


def generate_all(book_id: int | None = None) -> dict:
    """Generate markdown files for all (or one) book(s)."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    conn = sqlite3.Connection(DB_PATH)
    cursor = conn.cursor()

    if book_id:
        cursor.execute("SELECT id, title FROM books WHERE id = ?", (book_id,))
    else:
        cursor.execute("""
            SELECT b.id, b.title FROM books b
            JOIN clippings c ON b.id = c.book_id AND c.type = 'highlight'
            GROUP BY b.id HAVING COUNT(c.id) > 0
            ORDER BY b.title
        """)

    books = cursor.fetchall()
    stats = {'generated': 0, 'skipped': 0}

    for bid, title in books:
        md = generate_book_md(bid, conn)
        if md:
            filename = sanitize_filename(title) + ".md"
            output_path = OUTPUT_DIR / filename
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(md)
            stats['generated'] += 1
            print(f"  Generated: {filename}")
        else:
            stats['skipped'] += 1

    conn.close()
    return stats


def generate_library_index() -> dict:
    """Generate LIBRARY.md with Gemini-generated semantic fingerprints."""
    client = get_gemini_client()
    if not client:
        return {'error': 'GOOGLE_API_KEY not configured. Set it in .env file.'}

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.Connection(DB_PATH)
    cursor = conn.cursor()

    # Get all books with highlights
    cursor.execute("""
        SELECT b.id, b.title, b.author, b.summary,
               COUNT(c.id) as highlight_count,
               SUM(CASE WHEN c.rich_context IS NOT NULL THEN 1 ELSE 0 END) as nugget_count
        FROM books b
        JOIN clippings c ON b.id = c.book_id AND c.type = 'highlight'
        GROUP BY b.id HAVING highlight_count > 0
        ORDER BY b.title
    """)
    books = cursor.fetchall()

    # Build full title list for cross-book connections
    all_titles = [row[1] for row in books]
    title_list = "\n".join(f"- {t}" for t in all_titles)

    lines = []
    lines.append(f"# Kindle Brain Library — {len(books)} Books, Personal Reading Highlights")
    lines.append("")
    lines.append("## How to use this index")
    lines.append("Read each book's fingerprint to identify which books are relevant to a question.")
    lines.append("Books connect across multiple dimensions — a biography can teach about philosophy,")
    lines.append("a business book can teach about relationships. Think laterally.")
    lines.append("")
    lines.append("---")
    lines.append("")

    stats = {'generated': 0, 'failed': 0}

    for book_id, title, author, summary, highlight_count, nugget_count in books:
        # Get all highlight texts for this book
        cursor.execute("""
            SELECT c.text FROM clippings c
            WHERE c.book_id = ? AND c.type = 'highlight' AND c.text IS NOT NULL
            ORDER BY c.position_start
        """, (book_id,))
        highlights = [row[0] for row in cursor.fetchall()]
        highlights_text = "\n".join(f"- {h}" for h in highlights)

        # Generate fingerprint with Gemini
        prompt = f"""You are creating a personalized reading index entry. Given this book's summary AND the specific passages this reader highlighted, generate a semantic fingerprint.

BOOK: {title} by {author or 'Unknown'}
HIGHLIGHTS COUNT: {highlight_count}

BOOK SUMMARY:
{summary or 'No summary available.'}

READER'S HIGHLIGHTS (these are the specific passages they found important):
{highlights_text}

OTHER BOOKS IN THIS LIBRARY (for cross-references):
{title_list}

Generate the following sections. Be specific and personal — this is about what THIS reader took from the book, not a generic description. Write in English.

1. A 2-3 sentence description of the book focused on what the reader highlighted
2. "What this reader highlighted most" — the themes and ideas most important to this reader based on their highlights (2-4 sentences)
3. "These highlights help answer" — 4-6 questions that this reader's highlights would help answer (start each with "How", "What", "When", "Why", etc.)
4. "Key highlighted ideas" — 3-5 specific ideas, quotes, or concepts from the highlights
5. "Connects to" — 3-6 other books from the library list that connect to the themes in these highlights, with brief reason (e.g., "Zero to One (creating new things)")

Format your response exactly like this (no extra headers or markdown):
DESCRIPTION: [your 2-3 sentences]
HIGHLIGHTED_MOST: [your 2-4 sentences]
HELPS_ANSWER: [question 1] | [question 2] | [question 3] | ...
KEY_IDEAS: [idea 1] | [idea 2] | [idea 3] | ...
CONNECTS_TO: [Book Title (reason)] | [Book Title (reason)] | ..."""

        fingerprint = None
        for attempt in range(3):
            try:
                response = client.models.generate_content(
                    model=SUMMARY_MODEL,
                    contents=prompt,
                )
                fingerprint = response.text.strip()
                break
            except Exception as e:
                error_str = str(e)
                if '429' in error_str or 'RESOURCE_EXHAUSTED' in error_str:
                    wait = 15 * (attempt + 1)
                    print(f"  Rate limited, waiting {wait}s...")
                    time.sleep(wait)
                else:
                    print(f"  Error generating fingerprint for '{title}': {e}")
                    break

        if fingerprint:
            # Parse structured response
            parsed = _parse_fingerprint(fingerprint)
            author_str = f" — {author}" if author else ""
            lines.append(f"## {title}{author_str} ({highlight_count} highlights)")
            lines.append(parsed['description'])
            lines.append("")
            lines.append(f"**What this reader highlighted most**: {parsed['highlighted_most']}")
            lines.append("")
            lines.append(f"**These highlights help answer**: {parsed['helps_answer']}")
            lines.append("")
            lines.append(f"**Key highlighted ideas**: {parsed['key_ideas']}")
            lines.append("")
            lines.append(f"**Connects to**: {parsed['connects_to']}")
            lines.append("")
            lines.append("---")
            lines.append("")
            stats['generated'] += 1
            print(f"  Fingerprint: {title} ({highlight_count} highlights)")
        else:
            # Fallback: basic entry without LLM
            author_str = f" — {author}" if author else ""
            lines.append(f"## {title}{author_str} ({highlight_count} highlights)")
            if summary:
                lines.append(summary[:300])
            lines.append("")
            lines.append("---")
            lines.append("")
            stats['failed'] += 1
            print(f"  Fallback (no fingerprint): {title}")

        # Small delay between API calls
        time.sleep(1)

    output_path = OUTPUT_DIR / "LIBRARY.md"
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))

    conn.close()
    print(f"\nLibrary index: {output_path}")
    return stats


def _parse_fingerprint(text: str) -> dict:
    """Parse the structured fingerprint response from Gemini."""
    result = {
        'description': '',
        'highlighted_most': '',
        'helps_answer': '',
        'key_ideas': '',
        'connects_to': '',
    }

    for line in text.split('\n'):
        line = line.strip()
        if line.startswith('DESCRIPTION:'):
            result['description'] = line[len('DESCRIPTION:'):].strip()
        elif line.startswith('HIGHLIGHTED_MOST:'):
            result['highlighted_most'] = line[len('HIGHLIGHTED_MOST:'):].strip()
        elif line.startswith('HELPS_ANSWER:'):
            result['helps_answer'] = line[len('HELPS_ANSWER:'):].strip()
        elif line.startswith('KEY_IDEAS:'):
            result['key_ideas'] = line[len('KEY_IDEAS:'):].strip()
        elif line.startswith('CONNECTS_TO:'):
            result['connects_to'] = line[len('CONNECTS_TO:'):].strip()

    # If parsing failed, use the raw text as description
    if not result['description'] and text:
        result['description'] = text[:500]

    return result


def _parse_library_entries() -> list[dict]:
    """Parse LIBRARY.md into structured entries."""
    library_path = OUTPUT_DIR / "LIBRARY.md"
    if not library_path.exists():
        return []

    text = library_path.read_text(encoding='utf-8')
    # Split on --- separators
    blocks = re.split(r'\n---\s*\n', text)

    entries = []
    for block in blocks:
        block = block.strip()
        # Must start with ## (book entry header)
        header_match = re.match(
            r'^##\s+[\ufeff]?(.+?)(?:\s*—\s*(.+?))?\s*\((\d+)\s*highlights?\)',
            block
        )
        if not header_match:
            continue

        title = header_match.group(1).strip().lstrip('\ufeff')
        author = (header_match.group(2) or '').strip()
        highlight_count = int(header_match.group(3))

        # Extract fields
        entry = {
            'title': title,
            'author': author,
            'highlights': highlight_count,
            'description': '',
            'highlighted_most': '',
            'helps_answer': '',
            'key_ideas': '',
            'connects_to': '',
        }

        # Get description: text between header line and first **bold** field
        lines = block.split('\n')
        desc_lines = []
        past_header = False
        for line in lines:
            if line.startswith('## '):
                past_header = True
                continue
            if past_header and line.startswith('**'):
                break
            if past_header and line.strip():
                desc_lines.append(line.strip())
        entry['description'] = ' '.join(desc_lines)

        # Extract bold fields
        for field, key in [
            ('What this reader highlighted most', 'highlighted_most'),
            ('These highlights help answer', 'helps_answer'),
            ('Key highlighted ideas', 'key_ideas'),
            ('Connects to', 'connects_to'),
        ]:
            pattern = rf'\*\*{re.escape(field)}\*\*:\s*(.+?)(?=\n\n|\n\*\*|\Z)'
            match = re.search(pattern, block, re.DOTALL)
            if match:
                entry[key] = match.group(1).strip()

        entries.append(entry)

    return entries


def generate_catalog() -> dict:
    """Generate CATALOG.md — compact catalog using LLM compression of LIBRARY.md fingerprints."""
    client = get_gemini_client()
    if not client:
        return {'error': 'GOOGLE_API_KEY not configured. Set it in .env file.'}

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    entries = _parse_library_entries()
    if not entries:
        return {'error': 'LIBRARY.md not found or empty. Generate it first with --library-index'}

    lines = []
    lines.append(f"# Kindle Brain Catalog — {len(entries)} Books")
    lines.append("")
    lines.append("Compact index for navigation. Each entry has a personalized description,")
    lines.append("semantic tags, and cross-book links. Think LATERALLY: a Nike biography")
    lines.append("(Shoe Dog) is relevant to \"entrepreneurship\", a philosophy book (Meditations)")
    lines.append("is relevant to \"leadership under pressure\".")
    lines.append("")
    lines.append("After identifying 5-8 relevant books, read each book's full file for")
    lines.append("highlights, chapter summaries, and golden nuggets.")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Process in batches of 10 for efficiency
    batch_size = 10
    stats = {'generated': 0, 'failed': 0}

    for i in range(0, len(entries), batch_size):
        batch = entries[i:i + batch_size]
        batch_input = _format_batch_for_compression(batch)

        compressed = None
        for attempt in range(3):
            try:
                response = client.models.generate_content(
                    model=SUMMARY_MODEL,
                    contents=_build_catalog_prompt(batch_input, len(batch)),
                )
                compressed = response.text.strip()
                break
            except Exception as e:
                error_str = str(e)
                if '429' in error_str or 'RESOURCE_EXHAUSTED' in error_str:
                    wait = 15 * (attempt + 1)
                    print(f"  Rate limited, waiting {wait}s...")
                    time.sleep(wait)
                else:
                    print(f"  Error compressing batch {i // batch_size + 1}: {e}")
                    break

        if compressed:
            # Validate we got the right number of entries
            entry_count = compressed.count('\n## ')
            if not compressed.startswith('## '):
                entry_count += 0
            else:
                entry_count = compressed.count('## ')
            lines.append(compressed)
            lines.append("")
            if not compressed.rstrip().endswith('---'):
                lines.append("---")
                lines.append("")
            stats['generated'] += len(batch)
            print(f"  Batch {i // batch_size + 1}: {len(batch)} books compressed")
        else:
            # Fallback: mechanical compression for failed batches
            for entry in batch:
                fallback = _fallback_compress(entry)
                lines.append(fallback)
                lines.append("")
                lines.append("---")
                lines.append("")
            stats['failed'] += len(batch)
            print(f"  Batch {i // batch_size + 1}: FAILED, using fallback")

        time.sleep(1)

    output_path = OUTPUT_DIR / "CATALOG.md"
    content = "\n".join(lines)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"\nCatalog: {output_path} ({len(content)} chars, {len(entries)} books)")
    return {'generated': stats['generated'], 'failed': stats['failed'], 'chars': len(content)}


def _format_batch_for_compression(entries: list[dict]) -> str:
    """Format a batch of parsed library entries as input for the LLM compression prompt."""
    parts = []
    for entry in entries:
        author_str = f" — {entry['author']}" if entry['author'] else ""
        block = f"## {entry['title']}{author_str} ({entry['highlights']} highlights)\n"
        block += f"{entry['description']}\n"
        if entry['highlighted_most']:
            block += f"**What this reader highlighted most**: {entry['highlighted_most']}\n"
        if entry['helps_answer']:
            block += f"**These highlights help answer**: {entry['helps_answer']}\n"
        if entry['key_ideas']:
            block += f"**Key highlighted ideas**: {entry['key_ideas']}\n"
        if entry['connects_to']:
            block += f"**Connects to**: {entry['connects_to']}\n"
        parts.append(block)
    return "\n---\n\n".join(parts)


def _build_catalog_prompt(batch_input: str, count: int) -> str:
    """Build the LLM prompt for compressing fingerprints into catalog entries."""
    return f"""Compress {count} book fingerprints into a compact navigation catalog for an LLM.

EXACT format per entry:

## Title — Author (Nh)
One sentence: what THIS reader took from the book. Be vivid and specific — use the author's concepts, not generic summaries. Max 150 characters.
**Tags**: 5-6 lowercase tags, comma-separated. Mix topic tags with reader-specific angles. Example: "entrepreneurship, near-bankruptcy, zen philosophy, founder memoir, irrational persistence"
**Links**: Title1, Title2, Title3 (from "Connects to", titles only, no parenthetical reasons)

---

STRICT RULES:
- Use "Nh" (e.g. "29h"), not "N highlights"
- Description: ONE sentence only, max 150 characters. This is a catalog, not a review.
- Tags: 5-6 tags max. Lowercase. NO generic tags (book, reading, self-help, personal growth). Use the book's OWN vocabulary.
- Links: titles only, drop ALL parenthetical reasons
- Separate entries with ---
- Output ONLY entries. No preamble.

INPUT:

{batch_input}"""


def _fallback_compress(entry: dict) -> str:
    """Minimal mechanical fallback if LLM fails for an entry."""
    title = entry['title']
    author = entry['author']
    h = entry['highlights']
    author_str = f" — {author}" if author else ""
    header = f"## {title}{author_str} ({h}h)"

    desc = entry['description']
    sentences = re.split(r'(?<=[.!?])\s+', desc)
    short_desc = sentences[0] if sentences else desc
    if len(short_desc) > 200:
        short_desc = short_desc[:197] + '...'

    # Mechanical link extraction as fallback
    links = []
    if entry['connects_to']:
        for part in entry['connects_to'].split('|'):
            title_clean = re.sub(r'\s*\(.*?\)', '', part).strip().strip('., ')
            if title_clean:
                links.append(title_clean)
    links_line = f"**Links**: {', '.join(links)}" if links else ""

    parts = [header, short_desc]
    if links_line:
        parts.append(links_line)
    return '\n'.join(parts)


def embed_fingerprints() -> dict:
    """Regenerate all book .md files with fingerprint sections from LIBRARY.md."""
    entries = _parse_library_entries()
    if not entries:
        return {'error': 'LIBRARY.md not found or empty.'}

    # Build lookup by title (normalized)
    fingerprints = {}
    for entry in entries:
        key = entry['title'].lower().strip().lstrip('\ufeff')
        fingerprints[key] = entry

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.Connection(DB_PATH)
    cursor = conn.cursor()

    cursor.execute("""
        SELECT b.id, b.title FROM books b
        JOIN clippings c ON b.id = c.book_id AND c.type = 'highlight'
        GROUP BY b.id HAVING COUNT(c.id) > 0
        ORDER BY b.title
    """)
    books = cursor.fetchall()
    stats = {'updated': 0, 'no_fingerprint': 0}

    for bid, title in books:
        md = generate_book_md(bid, conn)
        if not md:
            continue

        # Find fingerprint for this book
        title_lower = title.lower().strip()
        fp = fingerprints.get(title_lower)

        # Try partial match if exact doesn't work
        if not fp:
            for key, entry in fingerprints.items():
                if key in title_lower or title_lower in key:
                    fp = entry
                    break

        if fp:
            # Insert fingerprint section after metadata, before Summary or ---
            fp_section = _format_fingerprint_section(fp)
            # Insert before "## Summary" or before first "---"
            if '\n## Summary\n' in md:
                md = md.replace('\n## Summary\n', f'\n{fp_section}\n## Summary\n', 1)
            elif '\n---\n' in md:
                md = md.replace('\n---\n', f'\n{fp_section}\n---\n', 1)
            stats['updated'] += 1
        else:
            stats['no_fingerprint'] += 1

        filename = sanitize_filename(title) + ".md"
        output_path = OUTPUT_DIR / filename
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(md)

    conn.close()
    print(f"Embedded fingerprints: {stats['updated']} books updated, "
          f"{stats['no_fingerprint']} without fingerprint")
    return stats


def _format_fingerprint_section(fp: dict) -> str:
    """Format a fingerprint dict as a markdown section."""
    lines = ["## Fingerprint", ""]
    if fp['highlighted_most']:
        lines.append(f"**What this reader highlighted most**: {fp['highlighted_most']}")
        lines.append("")
    if fp['helps_answer']:
        lines.append(f"**These highlights help answer**: {fp['helps_answer']}")
        lines.append("")
    if fp['key_ideas']:
        lines.append(f"**Key highlighted ideas**: {fp['key_ideas']}")
        lines.append("")
    if fp['connects_to']:
        lines.append(f"**Connects to**: {fp['connects_to']}")
        lines.append("")
    return '\n'.join(lines)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Generate Markdown files per book')
    parser.add_argument('--book', type=int, help='Generate only for this book_id')
    parser.add_argument('--library-index', action='store_true',
                        help='Generate LIBRARY.md with semantic fingerprints (requires Gemini API)')
    parser.add_argument('--catalog', action='store_true',
                        help='Generate CATALOG.md compact catalog from LIBRARY.md (Gemini Flash Lite)')
    parser.add_argument('--embed-fingerprints', action='store_true',
                        help='Regenerate book .md files with fingerprint sections from LIBRARY.md')
    args = parser.parse_args()

    if args.library_index:
        print("Generating LIBRARY.md with semantic fingerprints...")
        result = generate_library_index()
        if 'error' in result:
            print(f"Error: {result['error']}")
        else:
            print(f"Done! Generated: {result['generated']}, Failed: {result['failed']}")
    elif args.catalog:
        print("Generating CATALOG.md from LIBRARY.md...")
        result = generate_catalog()
        if 'error' in result:
            print(f"Error: {result['error']}")
        else:
            print(f"Done! {result['generated']} books, {result['chars']} chars")
    elif args.embed_fingerprints:
        print("Embedding fingerprints into book .md files...")
        result = embed_fingerprints()
        if 'error' in result:
            print(f"Error: {result['error']}")
        else:
            print(f"Done! Updated: {result['updated']}, No fingerprint: {result['no_fingerprint']}")
    else:
        print("Generating Markdown files...")
        result = generate_all(book_id=args.book)
        print(f"\nDone! Generated: {result['generated']}, Skipped: {result['skipped']}")
        print(f"Output: {OUTPUT_DIR}/")
